// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gridctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CGridctrl1

IMPLEMENT_DYNCREATE(CGridctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGridctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CGridctrl1 operations
