// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gridglctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CGridglctrl1

IMPLEMENT_DYNCREATE(CGridglctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGridglctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CGridglctrl1 operations
