// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "trendvaluegrid1.h"

/////////////////////////////////////////////////////////////////////////////
// CTrendvaluegrid1

IMPLEMENT_DYNCREATE(CTrendvaluegrid1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTrendvaluegrid1 properties

/////////////////////////////////////////////////////////////////////////////
// CTrendvaluegrid1 operations
