// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "trendgridctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CTrendgridctrl1

IMPLEMENT_DYNCREATE(CTrendgridctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTrendgridctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CTrendgridctrl1 operations
