// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "zindicatorctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CZindicatorctrl1

IMPLEMENT_DYNCREATE(CZindicatorctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CZindicatorctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CZindicatorctrl1 operations
