// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "zregulatorctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CZregulatorctrl1

IMPLEMENT_DYNCREATE(CZregulatorctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CZregulatorctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CZregulatorctrl1 operations
